default:
  image: node:14-alpine
  before_script:
    - apk add git ca-certificates
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  GITLAB_NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_NPM_CONFIG_REGISTRY: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
  NPMJS_NPM_TOKEN: ${NPMJS_NPM_TOKEN}
  NPMJS_CONFIG_REGISTRY: "https://registry.npmjs.org/"
  GITLAB_TOKEN: ${CI_JOB_TOKEN}

stages:
  - lint
  - test
  - build
  - deploy

.tests:
  dependencies: []
  only:
    - branches

linter_js:
  extends: .tests
  stage: lint
  script:
    - npm run lint

test:
  extends: .tests
  stage: test
  script:
    - npm run test:ci
  artifacts:
    reports:
      junit: junit.xml
      cobertura: coverage/cobertura-coverage.xml

npm-audit:
  extends: .tests
  allow_failure: true
  stage: test
  script:
    - npm audit

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - dist/

release:
  stage: deploy
  dependencies:
    - build
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
